# Generated by Django 4.2.25 on 2025-11-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=200)),
                ('description', models.TextField(help_text='Detailed course description')),
                ('for_who', models.CharField(choices=[('beginners', 'Beginners'), ('students', 'Students'), ('professionals', 'Professionals')], help_text='Target audience for this course', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Full name of the lead', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age of the lead')),
                ('phone', models.CharField(help_text='Phone number of the lead', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Lead',
                'verbose_name_plural': 'Course Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluses', models.JSONField(default=list, help_text="List of course advantages (e.g., ['mentor', 'project', 'team', 'certificate'])")),
                ('inthis_course', models.JSONField(default=list, help_text='List of objects with question and answer about course content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(help_text='Related course', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Detail',
                'verbose_name_plural': 'Course Details',
            },
        ),
    ]
