# Generated by Django 4.2.25 on 2025-11-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_for_who_forwho_coursepluses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question about course content', max_length=500)),
                ('answer', models.TextField(help_text='Answer to the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Related course', on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Course FAQ',
                'verbose_name_plural': 'Course FAQs',
            },
        ),
    ]
